services:
  db:
    image: postgres:15
    container_name: tmdb-postgres
    environment:
      POSTGRES_USER: tmdb
      POSTGRES_PASSWORD: tmdb
      POSTGRES_DB: tmdb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: